const sections={
  paintings:{image:'02_Kartiny.png',items:['Море в моём блокноте','Утренние цветы','Улочки с историей'],filters:['Все','Пейзажи','Эскизы']},
  photos:{image:'03_Fotografii.png',items:['Свет у окна','Соль и солнце','Городские детали','Тёплый вечер','Маленькие радости','Дом в кадре'],filters:['Места','Детали','Портреты']},
  travel:{image:'04_Puteshestviya.png',items:['Море в моём блокноте','Город в тёплых тонах','Горы, которые дышат тишиной'],filters:['Все истории','Море','Города','Природа']},
  style:{image:'05_Moy_stil.png',items:['Льняной день','Вечерний настрой','В ритме города'],filters:['Образы','Съёмки','Выбор Тани']}
};
const images=Object.values(sections).flatMap(s=>s.items.map(t=>({src:`assets/${s.image}`,title:t})));let lightIndex=0;
function panelShell(el){return `<div class="content-panel"><a class="back" href="#home">← В комнату</a><h2 class="page-heading">${el.dataset.title}</h2><p class="subtitle">${el.dataset.subtitle}</p><div class="slot"></div></div>`}
document.querySelectorAll('.panel-page').forEach(el=>el.innerHTML=panelShell(el));
for(const [id,data] of Object.entries(sections)){const el=document.querySelector(`#${id} .slot`);el.innerHTML=`<div class="filters">${data.filters.map((f,i)=>`<button class="${i?'':'active'}">${f}</button>`).join('')}</div><div class="gallery">${data.items.map((t,i)=>`<article class="card"><button data-lightbox="${images.findIndex(x=>x.title===t&&x.src.endsWith(data.image))}"><img src="assets/${data.image}" alt="${t}" style="object-position:${20+i*28}% center"><div class="card-copy"><h3>${t}</h3><p>Тёплая история, собранная из света, деталей и воспоминаний.</p></div></button></article>`).join('')}</div>`}
document.querySelector('#about .slot').innerHTML=`<div class="about-layout"><img src="assets/06_Obo_mne.png" alt="Таня в своей мастерской"><div><p>Этот проект — мой личный мир, где я делюсь вдохновением, картинами, историями и тем, как вижу красоту в обычных моментах.</p><p>Мне важно замечать детали, искать новые места, пробовать, творить и встречать интересных людей.</p><p><a class="button primary" href="#contact">Написать мне</a> <a class="button" href="#travel">Посмотреть истории</a></p></div></div>`;
document.querySelector('#personal .slot').innerHTML=`<div class="personal-grid"><article class="card locked"><a href="#love"><img src="assets/10_Lyubovnye_istorii.png" alt="Любовные истории"><div class="card-copy"><h3>Любовные истории</h3><p>О чувствах, встречах и невысказанных словах.</p></div></a></article><article class="card locked"><a href="#behind"><img src="assets/11_Za_kadrom.png" alt="За кадром"><div class="card-copy"><h3>За кадром</h3><p>Подготовка, образы и живые моменты.</p></div></a></article><article class="card locked"><img src="assets/09_Lichnoe.png" alt="Особые фотоистории"><div class="card-copy"><h3>Особые фотоистории</h3><p>Солнце, море и смелые образы.</p></div></article></div><div class="notice"><b>Раздел готовится.</b><br>Подписка пока недоступна.<br><button class="button primary notify">Сообщить об открытии</button></div>`;
for(const [id,img,title] of [['love','10_Lyubovnye_istorii.png','Письмо, которое я не отправила'],['behind','11_Za_kadrom.png','Выбираю образ']]){document.querySelector(`#${id} .slot`).innerHTML=`<div class="gallery"><article class="card"><button data-story><img src="assets/${img}" alt="${title}"><div class="card-copy"><h3>${title}</h3><p>Предпросмотр истории открыт. Продолжение появится в закрытом разделе.</p></div></button></article></div><div class="notice">Продолжение — в будущем закрытом разделе.<br><button class="button primary notify">Сообщить об открытии</button></div>`}
function form(id,collab=false){document.querySelector(`#${id} .slot`).innerHTML=`<div class="form-wrap"><div class="form-visual"><img src="assets/${collab?'08_Sotrudnichestvo.png':'07_Napisat_mne.png'}" alt="${collab?'Сотрудничество':'Написать Тане'}"></div><form class="form" data-kind="${collab?'collaboration':'message'}"><label>Имя${collab?' / бренд':''}<input name="name" required autocomplete="name"></label><label>Контакт для ответа<input name="contact" required placeholder="Email или @telegram"></label>${collab?'<label>Тип проекта<select name="type"><option>Рекламная интеграция</option><option>Контент для бренда</option><option>Fashion-съёмка</option><option>Совместный проект</option></select></label>':''}<label>${collab?'Описание предложения':'Сообщение'}<textarea name="message" required></textarea></label><label class="check"><input type="checkbox" name="consent" required> Согласие на обработку данных</label><button class="button primary" type="submit">${collab?'Отправить предложение':'Отправить сообщение'}</button><small>Форма будет отправлена через защищённый Telegram endpoint.</small></form></div>`}
form('contact');form('collab',true);
const lightbox=document.querySelector('#lightbox');function showLight(i){lightIndex=(i+images.length)%images.length;lightbox.querySelector('img').src=images[lightIndex].src;lightbox.querySelector('p').textContent=images[lightIndex].title;if(!lightbox.open)lightbox.showModal()}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-lightbox]');if(btn)showLight(+btn.dataset.lightbox);if(e.target.closest('.notify'))toast('Записали интерес. Подключение подписки появится после согласования сервиса.');const filter=e.target.closest('.filters button');if(filter){filter.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));filter.classList.add('active')}});
lightbox.querySelector('.close').onclick=()=>lightbox.close();lightbox.querySelector('.prev').onclick=()=>showLight(lightIndex-1);lightbox.querySelector('.next').onclick=()=>showLight(lightIndex+1);
function route(){const id=(location.hash||'#home').slice(1);document.querySelectorAll('.page').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${id}`));window.scrollTo(0,0)}window.addEventListener('hashchange',route);route();
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),4200)}
document.addEventListener('submit',async e=>{if(!e.target.matches('.form'))return;e.preventDefault();const form=e.target;if(!form.reportValidity())return;const endpoint=window.TANYA_TELEGRAM_ENDPOINT;if(!endpoint){toast('Форма проверена. Для реальной отправки нужен Telegram endpoint.');return}const payload=Object.fromEntries(new FormData(form));payload.kind=form.dataset.kind;try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error();form.reset();toast('Сообщение отправлено. Спасибо!')}catch{toast('Не удалось отправить. Проверьте соединение и попробуйте снова.')}});
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&lightbox.open)showLight(lightIndex-1);if(e.key==='ArrowRight'&&lightbox.open)showLight(lightIndex+1)});
