const galleryRoot='assets/gallery';
const sections={
paintings:{filters:['Все','Пейзажи','Эскизы'],items:[
['paintings/01_sea_notebook','Море в моём блокноте','Пейзажи','Средиземноморский город у синего моря, написанный живыми мазками.','Живописный средиземноморский город на склоне над синим морем'],
['paintings/02_morning_flowers','Утренние цветы','Эскизы','Пионы и ромашки в керамической вазе на солнечном подоконнике.','Картина с нежными пионами и белыми ромашками в керамической вазе'],
['paintings/03_streets_with_history','Улочки с историей','Эскизы','Тёплая европейская улочка с арками, цветами и далёким куполом.','Акварель старой европейской улочки с арками и цветочными горшками']]},
photos:{filters:['Все','Места','Детали','Портреты'],items:[
['photos/01_window_light','Свет у окна','Портреты','Тихий портрет у высокого окна в мягком естественном свете.','Таня сидит у высокого солнечного окна в уютной мастерской','50% 34%'],
['photos/02_salt_and_sun','Соль и солнце','Места','Солнечные волны Средиземного моря у светлого каменистого берега.','Синие морские волны разбиваются о светлый каменистый берег'],
['photos/03_city_details','Городские детали','Детали','Бирюзовая дверь, терракотовая стена и цветущая бугенвиллея.','Бирюзовая деревянная дверь и цветущая бугенвиллея на тёплой стене'],
['photos/04_warm_evening','Тёплый вечер','Портреты','Закат на балконе, морской ветер и лёгкое летнее платье.','Таня в терракотовом платье стоит на балконе у моря на закате','50% 28%'],
['photos/05_small_joys','Маленькие радости','Детали','Кофе, абрикосы, ромашки и плёночная камера в пятнах солнца.','Чашка кофе, абрикосы, ромашки и винтажная камера на деревянном столе'],
['photos/06_home_in_frame','Дом в кадре','Места','Солнечная мастерская с мольбертом, книгами, растениями и котом.','Уютная мастерская с окном, мольбертом, растениями и спящим котом']]},
travel:{filters:['Все','Море','Города','Природа'],items:[
['travel/01_sea_notebook','Море в моём блокноте','Море','Город над синей бухтой, лодки и бугенвиллея в золотом свете.','Средиземноморский город над синей бухтой с лодками и цветами'],
['travel/02_warm_city','Город в тёплых тонах','Города','Прогулка по старому городу среди охристых стен и узких улиц.','Таня оглядывается во время прогулки по тёплой улице старого города','50% 28%'],
['travel/03_quiet_mountains','Горы, которые дышат тишиной','Природа','Бирюзовое озеро, горные пики и мягкий утренний туман.','Драматичные горные вершины над бирюзовым альпийским озером']]},
style:{filters:['Все','Образы','Съёмки','Выбор Тани'],items:[
['style/01_linen_day','Льняной день','Образы','Белая льняная рубашка и свободные брюки для лёгкого дня.','Таня в белой льняной рубашке и светлых свободных брюках','50% 25%'],
['style/02_evening_mood','Вечерний настрой','Съёмки','Лаконичное чёрное платье и тёплый свет вечерней террасы.','Таня в элегантном чёрном платье на вечерней террасе','50% 22%'],
['style/03_city_rhythm','В ритме города','Выбор Тани','Жакет, прямые джинсы и белые кеды для прогулки по городу.','Таня идёт по городу в жакете, джинсах и белых кедах','50% 24%']]}};
const item=a=>({file:a[0],title:a[1],category:a[2],description:a[3],alt:a[4],position:a[5]||'50% 50%'});
const personal=[
{file:'personal/01_love_stories',title:'Любовные истории',description:'О чувствах, встречах и невысказанных словах.',alt:'Таня читает рукописное письмо у окна в тёплом вечернем свете',href:'#love',position:'50% 30%'},
{file:'personal/02_behind_scenes',title:'За кадром',description:'Подготовка, образы и живые моменты.',alt:'Чёрно-белый кадр подготовки Тани к съёмке',href:'#behind',position:'50% 25%'},
{file:'personal/03_special_photo_stories',title:'Особые фотоистории',description:'Солнце, море и смелые образы.',alt:'Таня на морском берегу в мягком солнечном свете',position:'50% 28%'}];
const lightItems=[];let lightIndex=0,lightTrigger=null;
const paths=file=>({original:`${galleryRoot}/${file}.png`,full:`${galleryRoot}/${file}.webp`,thumb:`${galleryRoot}/${file}_thumb.webp`});
const register=x=>(lightItems.push({...x,...paths(x.file)}),lightItems.length-1);
function media(x,index,href=''){const p=paths(x.file),pic=`<picture><source srcset="${p.thumb}" type="image/webp"><img src="${p.original}" data-fallback="${p.original}" alt="${x.alt}" width="720" height="480" loading="lazy" decoding="async" style="object-position:${x.position||'50% 50%'}"></picture>`;return href?`<a class="card-media" href="${href}" aria-label="Открыть раздел «${x.title}»">${pic}</a>`:`<button class="card-media" type="button" data-lightbox="${index}" aria-label="Открыть изображение «${x.title}» крупно">${pic}</button>`}
function shell(el){const nested=['love','behind'].includes(el.id);return `<div class="content-panel"><a class="back" href="${nested?'#personal':'#home'}">← ${nested?'В Личное':'В комнату'}</a><h2 class="page-heading" tabindex="-1">${el.dataset.title}</h2><p class="subtitle">${el.dataset.subtitle}</p><div class="slot"></div></div>`}
document.querySelectorAll('.panel-page').forEach(el=>el.innerHTML=shell(el));
for(const [id,data] of Object.entries(sections)){const list=data.items.map(item).map(x=>({...x,index:register(x)}));document.querySelector(`#${id} .slot`).innerHTML=`<div class="filters" role="group" aria-label="Фильтры раздела">${data.filters.map((f,i)=>`<button type="button" class="${i?'':'active'}" data-filter="${f}" aria-pressed="${i?'false':'true'}">${f}</button>`).join('')}</div><div class="gallery">${list.map(x=>`<article class="card" data-category="${x.category}">${media(x,x.index)}<div class="card-copy"><span class="category">${x.category}</span><h3>${x.title}</h3><p>${x.description}</p></div></article>`).join('')}</div><p class="empty-state" hidden>В этой категории пока нет материалов. Выберите «Все».</p>`}
document.querySelector('#about .slot').innerHTML=`<div class="about-layout"><picture><source srcset="assets/gallery/photos/01_window_light.webp" type="image/webp"><img src="assets/gallery/photos/01_window_light.png" alt="Таня у солнечного окна в своей творческой комнате" width="1536" height="1024" loading="lazy"></picture><div><p>Этот проект — мой личный мир, где я делюсь вдохновением, картинами, историями и тем, как вижу красоту в обычных моментах.</p><p>Мне важно замечать детали, искать новые места, пробовать и творить.</p><p class="button-row"><a class="button primary" href="#contact">Написать мне</a> <a class="button" href="#travel">Посмотреть истории</a></p></div></div>`;
document.querySelector('#personal .slot').innerHTML=`<div class="personal-grid">${personal.map(x=>{const i=register(x);return `<article class="card locked">${media(x,i,x.href)}<div class="card-copy"><h3>${x.title}</h3><p>${x.description}</p>${x.href?`<a class="card-link" href="${x.href}">Открыть доступный предпросмотр →</a>`:'<span class="soon">Материал готовится</span>'}</div></article>`}).join('')}</div><div class="notice"><b>Два предпросмотра уже доступны.</b><br>Подписка, платёж и защищённый доступ пока не реализованы.<br><button class="button notify" type="button">Как узнать об открытии?</button></div>`;
const stories={love:{...personal[0],title:'Письмо, которое я не отправила',preview:'Иногда всё начинается с простого привета. А потом ловишь себя на том, что ждёшь следующего сообщения. Этот небольшой фрагмент — открытая часть будущей истории.'},behind:{...personal[1],title:'Выбираю образ',preview:'Перед съёмкой остаются тихие минуты: выбрать одежду, проверить свет и привыкнуть к настроению кадра. Здесь открыт короткий фрагмент подготовки.'}};
for(const [id,x] of Object.entries(stories)){const i=register(x);document.querySelector(`#${id} .slot`).innerHTML=`<div class="story-preview">${media(x,i)}<article><span class="category">Открытый предпросмотр</span><h3>${x.title}</h3><p>${x.preview}</p><p class="preview-note">Продолжение пока не опубликовано. Платный или защищённый доступ не подключён.</p></article></div><div class="notice"><button class="button notify" type="button">Как узнать об открытии?</button></div>`}
function field(prefix,name,label,control){return `<label class="field">${label}${control}<span class="field-error" id="${prefix}-${name}-error"></span></label>`}
function form(id,collab=false){const illustration=collab?'style/03_city_rhythm':'photos/05_small_joys',error=n=>`${id}-${n}-error`;document.querySelector(`#${id} .slot`).innerHTML=`<div class="form-wrap"><div class="form-visual"><picture><source srcset="${galleryRoot}/${illustration}.webp" type="image/webp"><img src="${galleryRoot}/${illustration}.png" alt="${collab?'Городской образ для творческого сотрудничества':'Кофе, ромашки и камера рядом с письмом'}" width="1536" height="1024" loading="lazy"></picture></div><form class="form" data-kind="${collab?'collaboration':'message'}" data-prefix="${id}" novalidate><div class="form-status" role="status">Онлайн-отправка пока не подключена. Заполненные данные никуда не отправятся.</div>${field(id,'name',`Имя${collab?' / бренд':''}`,`<input name="name" required autocomplete="name" aria-describedby="${error('name')}">`)}${field(id,'contact','Контакт для ответа',`<input name="contact" required placeholder="email или @telegram" aria-describedby="${error('contact')}">`)}${collab?'<label class="field">Тип проекта<select name="type"><option>Рекламная интеграция</option><option>Контент для бренда</option><option>Fashion-съёмка</option><option>Совместный проект</option></select></label>':''}${field(id,'message',collab?'Описание предложения':'Сообщение',`<textarea name="message" required aria-describedby="${error('message')}"></textarea>`)}<label class="check"><input type="checkbox" name="consent" required aria-describedby="${error('consent')}"> <span>Я согласен(на) на обработку данных. <strong>Документ об обработке данных пока не опубликован.</strong></span></label><span class="field-error" id="${error('consent')}"></span><button class="button primary" type="submit">${collab?'Отправить предложение':'Отправить сообщение'}</button><small>После подключения формы Таня сможет ответить по указанному контакту.</small></form></div>`}form('contact');form('collab',true);
const lightbox=document.querySelector('#lightbox'),lightImg=lightbox.querySelector('img');
function showLight(i,trigger=document.activeElement){lightIndex=(i+lightItems.length)%lightItems.length;lightTrigger=trigger instanceof HTMLElement?trigger:lightTrigger;const x=lightItems[lightIndex];lightImg.classList.remove('image-error');lightImg.alt=x.alt;lightImg.dataset.fallback=x.original;delete lightImg.dataset.fallbackUsed;lightImg.src=x.full;lightbox.querySelector('p').textContent=x.title;if(!lightbox.open)lightbox.showModal();lightbox.querySelector('.close').focus()}
function closeLight(){if(lightbox.open)lightbox.close()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-lightbox]');if(b)showLight(+b.dataset.lightbox,b);if(e.target.closest('.notify'))toast('Сбор уведомлений пока не подключён. Для него нужен серверный обработчик и политика обработки данных.');const f=e.target.closest('[data-filter]');if(f){const controls=f.closest('.filters'),gallery=controls.nextElementSibling;controls.querySelectorAll('button').forEach(b=>{const on=b===f;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});gallery.querySelectorAll('.card').forEach(c=>c.hidden=f.dataset.filter!=='Все'&&c.dataset.category!==f.dataset.filter);const empty=gallery.nextElementSibling;empty.hidden=gallery.querySelectorAll('.card:not([hidden])').length>0}});
document.addEventListener('error',e=>{const img=e.target;if(!(img instanceof HTMLImageElement))return;const fallback=img.dataset.fallback;if(fallback&&!img.dataset.fallbackUsed){img.dataset.fallbackUsed='true';img.src=fallback;return}img.classList.add('image-error');img.alt=`Изображение «${img.alt}» временно недоступно`},true);
lightbox.querySelector('.close').onclick=closeLight;lightbox.querySelector('.prev').onclick=()=>showLight(lightIndex-1);lightbox.querySelector('.next').onclick=()=>showLight(lightIndex+1);lightbox.addEventListener('close',()=>lightTrigger?.focus());lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLight()});
const menu=document.querySelector('.menu-button');menu.onclick=()=>{const open=document.body.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню')};document.querySelector('.desktop-nav').onclick=()=>{document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false')};
function route(initial=false){const requested=(location.hash||'#home').slice(1),target=document.getElementById(requested),id=target?.classList.contains('page')?requested:'home';document.querySelectorAll('.page').forEach(s=>{const active=s.id===id;s.classList.toggle('active',active);if(active)s.scrollTop=0});document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${id}`));document.querySelector(`#${id} .page-heading`)?.focus({preventScroll:true});document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');if(!initial&&requested!==id)history.replaceState(null,'','#home')}window.addEventListener('hashchange',()=>route());route(true);
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),4200)}
function validate(form){form.querySelectorAll('.field-error').forEach(x=>x.textContent='');let first=null;const set=(name,msg)=>{const control=form.elements[name],error=form.querySelector(`#${form.dataset.prefix}-${name}-error`);if(error)error.textContent=msg;control?.setAttribute('aria-invalid','true');first??=control};['name','contact','message'].forEach(name=>form.elements[name]?.removeAttribute('aria-invalid'));if(!form.elements.name.value.trim())set('name','Укажите имя.');const contact=form.elements.contact.value.trim();if(!contact)set('contact','Укажите контакт для ответа.');else if(!/^(?:[^\s@]+@[^\s@]+\.[^\s@]+|@[A-Za-z0-9_]{5,}|https?:\/\/t\.me\/[A-Za-z0-9_]{5,})$/.test(contact))set('contact','Введите email, @telegram или ссылку t.me.');if(!form.elements.message.value.trim())set('message','Напишите сообщение.');if(!form.elements.consent.checked)set('consent','Без согласия отправка невозможна.');first?.focus();return !first}
document.addEventListener('submit',async e=>{if(!e.target.matches('.form'))return;e.preventDefault();const form=e.target;if(!validate(form))return;const endpoint=window.TANYA_TELEGRAM_ENDPOINT,status=form.querySelector('.form-status'),button=form.querySelector('[type="submit"]');if(!endpoint){status.textContent='Отправка недоступна: нужен серверный Telegram endpoint и опубликованный документ об обработке данных.';status.classList.add('error');return}const payload=Object.fromEntries(new FormData(form));payload.kind=form.dataset.kind;button.disabled=true;button.textContent='Отправляем…';status.textContent='Отправка сообщения…';status.classList.remove('error');try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error(`HTTP ${res.status}`);form.reset();status.textContent='Сообщение принято сервером. Спасибо!';toast('Сообщение принято сервером.')}catch{status.textContent='Сервер не подтвердил получение. Данные сохранены в форме — попробуйте позже.';status.classList.add('error')}finally{button.disabled=false;button.textContent=form.dataset.kind==='collaboration'?'Отправить предложение':'Отправить сообщение'}});
document.addEventListener('keydown',e=>{if(!lightbox.open)return;if(e.key==='ArrowLeft')showLight(lightIndex-1);if(e.key==='ArrowRight')showLight(lightIndex+1);if(e.key==='Escape')closeLight()});
